version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9092
    restart: on-failure

  transformer-1:
    build:
      context: .
      dockerfile: Dockerfile.transformer
    depends_on:
      - kafka
      - producer
    environment:
      - KAFKA_BROKERS=kafka:9092
      - INSTANCE=1
    restart: on-failure

  transformer-2:
    build:
      context: .
      dockerfile: Dockerfile.transformer
    depends_on:
      - kafka
      - producer
    environment:
      - KAFKA_BROKERS=kafka:9092
      - INSTANCE=2
    restart: on-failure

  transformer-3:
    build:
      context: .
      dockerfile: Dockerfile.transformer
    depends_on:
      - kafka
      - producer
    environment:
      - KAFKA_BROKERS=kafka:9092
      - INSTANCE=3
    restart: on-failure

  publisher-1:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    depends_on:
      - kafka
      - transformer-1
    environment:
      - KAFKA_BROKERS=kafka:9092
      - INSTANCE=1
    volumes:
      - ./output:/app/output
    restart: on-failure

  publisher-2:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    depends_on:
      - kafka
      - transformer-1
    environment:
      - KAFKA_BROKERS=kafka:9092
      - INSTANCE=2
    volumes:
      - ./output:/app/output
    restart: on-failure

  publisher-3:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    depends_on:
      - kafka
      - transformer-1
    environment:
      - KAFKA_BROKERS=kafka:9092
      - INSTANCE=3
    volumes:
      - ./output:/app/output
    restart: on-failure

volumes:
  kafka_data:
    driver: local